[package]
name = "oxigen"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs = { path = "../ecs" }
app = { path = "../app" }
runner = { path = "../runner" }
input = { path = "../input" }
render_2d = { path = "../render_2d" }
