[workspace]
resolver = "2"
members = [
  "app",
  "derive",
  "ecs",
  "engine_testing/test_input",
  "input",
  "oxigen",
  "render_2d",
  "test_suite",
  "runner", "engine_testing/basic_2d_render"
]
