[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
ecs = { path = "../ecs" }
app = { path = "../app" }
env_logger = "0.10"
winit_input_helper = "0.14"
input = { path = "../input" }
render_2d = { path = "../render_2d" }
